### ISSUE TITLE
Servitudes is plural, should be singular

### ISSUE THREAD

**Issue by EricBos** [ibpdi/cdm#13]
Should the object Servitudes not be named Servitude?
It's the only entity that is named plural.

**Comment by bm-joshuathiele** [comment]
Thanks a lot for the input. It should be singular you are completely right. It will be updated with the next release within June

**Comment by bm-joshuathiele** [comment]
Hi EricBos,
the issue has been updated with the IBPDI Real Estate CDM update Version : 2.0 release. Thanks a lot again for pointing it out.
Kind regards

**Comment by EricBos** [comment]
Awesome! I will look at the new release asap.
Cheers,

Eric
________________________________

Met vriendelijke groet,
ing. Eric Bos 
Partner
T: +31 20 658 95 98 | M: +31 611 741 719
***@***.***
springrealestate.com | 
LinkedIn | 
Facebook | 
Instagram
Spring Technologies B.V.
Laan der Hesperiden 68
 | 
1076 DX | 
Amsterdam
Spring Technologies B.V. is onderdeel van Spring Services B.V. , ingeschreven in het handelsregister van de Kamer van 
​Koophandel te Amsterdam onder nr. 84133600.

​Disclaimer - Deze email en mogelijk meegezonden bestanden zijn vertrouwelijk en bevatten informatie die alleen bedoeld is 
​voor de geadresseerde. Heeft u deze email ontvangen en bent u niet de geadresseerde, stel dan de zender van de email op de 
​hoogte via email of telefoon (+31 (0)20 658 95 98) en verwijder deze email van uw systeem. Wij kunnen niet garanderen dat 
​deze email en mogelijk meegezonden bestanden virusvrij zijn, ondanks dat wij daar grote zorg aan besteden om dit risico zo 
​beperkt mogelijk te houden.

**Comment by bm-joshuathiele** [comment]
Thanks a lot. The reviews are very much appreciated. If you find anything or have some open questions I am happy to answer them any time.
