### ISSUE TITLE
AreaMeasurement.cdm.json contains duplicate enum values

### ISSUE THREAD

**Issue by EricBos** [ibpdi/cdm#15]
{
              "languageTag": "en",
              "displayText": "Rentable area exclusive occupancy",
              "attributeValue": "Rentable area exclusive occupancy",
              "displayOrder": "16"
            },

as the same as

  {
              "languageTag": "en",
              "displayText": "Rentable area exclusive occupancy",
              "attributeValue": "Rentable area exclusive occupancy",
              "displayOrder": "33"
            },

as well as
 {
              "languageTag": "en",
              "displayText": "Rentable area common occupancy",
              "attributeValue": "Rentable area common occupancy",
              "displayOrder": "15"
            },

is the same as 
 {
              "languageTag": "en",
              "displayText": "Rentable area common occupancy",
              "attributeValue": "Rentable area common occupancy",
              "displayOrder": "29"
            },

**Comment by bm-joshuathiele** [comment]
Thanks for pointing this out. We have fixed it in the feature update last week
