### ISSUE TITLE
Dunning does not reference the RentalPayment correcty / PK/FK not matching

### ISSUE THREAD

**Issue by EricBos** [ibpdi/cdm#16]
Dunning has a FK relationship with RentalPayment by the RentalPaymentId

The RentalPayment has 2 fields in the Primary Key:
- RentalPaymentId
- RentalContractId

This will not work.
I think the RentalContractId in the RentalPayment entity should be a FK instead.

**Comment by bm-joshuathiele** [comment]
This has been fixed in the feature update last week
