### ISSUE TITLE
share graphical representation of the data model 

### ISSUE THREAD

**Issue by oli99sc** [ibpdi/cdm#3]
During the launch event, a visualization of the data model was shared (although it was not up to date). 
Would be great to have this being part of the docs. 

Thx

**Comment by oli99sc** [comment]
Ah, I understand that the visual is part of https://github.com/ibpdi/cdm/blob/main/Documentation/CDM_V01_documentation.html but this file is to big to be displayed in github directly. Maybe consider adding a public site for this repo or do not use single file with embedded images, instead store images as dedicated files.

**Comment by BuildingMindsJT** [comment]
We added a seperat[ link ](https://ibpdi.github.io/)to open the page. Or see the README in the Documentation folder.
